In [1]:
import numpy as np #import libary

##### Check numpy version. There have been significant changes since numpy 1.18. Numpy installations less than 1.18 should be upgraded to a later version.

In [2]:
np.version.version #determine numpy version 

'1.20.1'

In [3]:
a=np.random.rand(5,2) 

In [4]:
print(a)

[[0.41567441 0.206824  ]
 [0.14934281 0.49144385]
 [0.46927398 0.59372798]
 [0.27166665 0.17499883]
 [0.6182185  0.82396385]]


### Simple Random data functions.

#### 1. Integers

In [6]:
#https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html#numpy.random.Generator.integers
rng = np.random.default_rng() 
#create an array of 10 items with a range of random integers between 0 & 1 (2)
rng.integers(2, size=10)

array([1, 1, 0, 1, 1, 0, 0, 0, 1, 1], dtype=int64)

In [7]:
#create an array of 10 items with a range of random integers between 0 & 0 (1)
rng.integers(1, size=10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [8]:
#create a two lists of integers each with four items array with a range of integers between 0 & 4 (5)
rng.integers(5, size=(2, 4))

array([[0, 4, 1, 2],
       [0, 1, 3, 2]], dtype=int64)